export interface Country {
    code: string
    name: string
    dial: string
}

export const popularCountries: Country[] = [
    { code: 'YE', name: 'اليمن', dial: '+967' },
    { code: 'SA', name: 'السعودية', dial: '+966' },
    { code: 'AE', name: 'الإمارات', dial: '+971' },
    { code: 'KW', name: 'الكويت', dial: '+965' },
    { code: 'QA', name: 'قطر', dial: '+974' },
    { code: 'BH', name: 'البحرين', dial: '+973' },
    { code: 'OM', name: 'عمان', dial: '+968' },
    { code: 'JO', name: 'الأردن', dial: '+962' },
    { code: 'EG', name: 'مصر', dial: '+20' },
    { code: 'IQ', name: 'العراق', dial: '+964' },
]

export const allCountries: Country[] = [
    { code: 'SA', name: 'السعودية', dial: '+966' },
    { code: 'YE', name: 'اليمن', dial: '+967' },
    { code: 'AE', name: 'الإمارات', dial: '+971' },
    { code: 'KW', name: 'الكويت', dial: '+965' },
    { code: 'QA', name: 'قطر', dial: '+974' },
    { code: 'BH', name: 'البحرين', dial: '+973' },
    { code: 'OM', name: 'عمان', dial: '+968' },
    { code: 'JO', name: 'الأردن', dial: '+962' },
    { code: 'EG', name: 'مصر', dial: '+20' },
    { code: 'IQ', name: 'العراق', dial: '+964' },
    { code: 'LB', name: 'لبنان', dial: '+961' },
    { code: 'SY', name: 'سوريا', dial: '+963' },
    { code: 'PS', name: 'فلسطين', dial: '+970' },
    { code: 'DZ', name: 'الجزائر', dial: '+213' },
    { code: 'MA', name: 'المغرب', dial: '+212' },
    { code: 'TN', name: 'تونس', dial: '+216' },
    { code: 'LY', name: 'ليبيا', dial: '+218' },
    { code: 'SD', name: 'السودان', dial: '+249' },
    { code: 'MR', name: 'موريتانيا', dial: '+222' },
    { code: 'SO', name: 'الصومال', dial: '+252' },
    { code: 'DJ', name: 'جيبوتي', dial: '+253' },
    { code: 'KM', name: 'جزر القمر', dial: '+269' },
    { code: 'TR', name: 'تركيا', dial: '+90' },
    { code: 'US', name: 'الولايات المتحدة', dial: '+1' },
    { code: 'GB', name: 'المملكة المتحدة', dial: '+44' },
    { code: 'CA', name: 'كندا', dial: '+1' },
    { code: 'DE', name: 'ألمانيا', dial: '+49' },
    { code: 'FR', name: 'فرنسا', dial: '+33' },
    { code: 'ES', name: 'إسبانيا', dial: '+34' },
    { code: 'IT', name: 'إيطاليا', dial: '+39' },
    { code: 'CN', name: 'الصين', dial: '+86' },
    { code: 'IN', name: 'الهند', dial: '+91' },
    { code: 'ID', name: 'إندونيسيا', dial: '+62' },
    { code: 'MY', name: 'ماليزيا', dial: '+60' },
    { code: 'PK', name: 'باكستان', dial: '+92' },
    { code: 'BD', name: 'بنجلاديش', dial: '+880' },
    { code: 'RU', name: 'روسيا', dial: '+7' },
    { code: 'BR', name: 'البرازيل', dial: '+55' },
    { code: 'MX', name: 'المكسيك', dial: '+52' },
    { code: 'JP', name: 'اليابان', dial: '+81' },
    { code: 'KR', name: 'كوريا الجنوبية', dial: '+82' },
    { code: 'AU', name: 'أستراليا', dial: '+61' },
    { code: 'NZ', name: 'نيوزيلندا', dial: '+64' },
    { code: 'ZA', name: 'جنوب أفريقيا', dial: '+27' },
    { code: 'NG', name: 'نيجيريا', dial: '+234' },
    { code: 'ET', name: 'إثيوبيا', dial: '+251' },
    { code: 'KE', name: 'كينيا', dial: '+254' },
    { code: 'TZ', name: 'تنزانيا', dial: '+255' },
    { code: 'UG', name: 'أوغندا', dial: '+256' },
    { code: 'GH', name: 'غانا', dial: '+233' },
    { code: 'CI', name: 'ساحل العاج', dial: '+225' },
    { code: 'SN', name: 'السنغال', dial: '+221' },
    { code: 'PT', name: 'البرتغال', dial: '+351' },
    { code: 'NL', name: 'هولندا', dial: '+31' },
    { code: 'BE', name: 'بلجيكا', dial: '+32' },
    { code: 'CH', name: 'سويسرا', dial: '+41' },
    { code: 'AT', name: 'النمسا', dial: '+43' },
    { code: 'SE', name: 'السويد', dial: '+46' },
    { code: 'NO', name: 'النرويج', dial: '+47' },
    { code: 'DK', name: 'الدنمارك', dial: '+45' },
    { code: 'FI', name: 'فنلندا', dial: '+358' },
    { code: 'IE', name: 'أيرلندا', dial: '+353' },
    { code: 'GR', name: 'اليونان', dial: '+30' },
    { code: 'PL', name: 'بولندا', dial: '+48' },
    { code: 'RO', name: 'رومانيا', dial: '+40' },
    { code: 'CZ', name: 'التشيك', dial: '+420' },
    { code: 'HU', name: 'المجر', dial: '+36' },
    { code: 'UA', name: 'أوكرانيا', dial: '+380' },
    { code: 'TH', name: 'تايلاند', dial: '+66' },
    { code: 'VN', name: 'فيتنام', dial: '+84' },
    { code: 'PH', name: 'الفلبين', dial: '+63' },
    { code: 'SG', name: 'سنغافورة', dial: '+65' },
    { code: 'HK', name: 'هونغ كونغ', dial: '+852' },
    { code: 'TW', name: 'تايوان', dial: '+886' },
    { code: 'IR', name: 'إيران', dial: '+98' },
    { code: 'AF', name: 'أفغانستان', dial: '+93' },
    { code: 'LK', name: 'سريلانكا', dial: '+94' },
    { code: 'NP', name: 'نيبال', dial: '+977' },
    { code: 'MM', name: 'ميانمار', dial: '+95' },
    { code: 'KH', name: 'كمبوديا', dial: '+855' },
    { code: 'LA', name: 'لاوس', dial: '+856' },
].sort((a, b) => a.name.localeCompare(b.name, 'ar'))
