name: Aymili PDP Test

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecom
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build API
        run: pnpm -w -r -F @repo/api build

      - name: Prepare database schema (Prisma migrate)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ecom
          DIRECT_URL: postgresql://postgres:postgres@localhost:5432/ecom
        run: |
          npx -y prisma@5.14.0 migrate deploy --schema packages/db/prisma/schema.prisma

      - name: Start API
        run: |
          export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/ecom
          export DIRECT_URL=${DATABASE_URL}
          export JWT_SECRET=ci_test_secret
          export ADMIN_EMAIL='${{ secrets.ADMIN_EMAIL }}'
          export ADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}'
          export MAINTENANCE_SECRET=maint_ci
          node packages/api/dist/index.js &
          echo $! > api.pid
          # wait for health
          for i in {1..30}; do
            curl -fsS http://127.0.0.1:4000/health && break || sleep 1;
          done

      - name: Ensure admin exists (maintenance endpoint)
        run: |
          curl -fsS -X POST "http://127.0.0.1:4000/api/admin/maintenance/create-admin" \
            -H 'content-type: application/json' \
            -H 'x-maintenance-secret: maint_ci' \
            -d '{"email":"'${{ secrets.ADMIN_EMAIL }}'","password":"'${{ secrets.ADMIN_PASSWORD }}'","name":"CI Admin"}'

      - name: Create Aymili product and verify
        env:
          API_BASE: http://127.0.0.1:4000
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: node scripts/ci/create-aymili-product.mjs

      - name: Stop API
        if: always()
        run: |
          if [ -f api.pid ]; then kill $(cat api.pid) || true; fi
