name: CI - Admin Modules

on:
  push:
    branches:
      - feature/admin-non-product-modules

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PostgreSQL (no Docker)
        uses: shogo82148/actions-setup-postgresql@v1
        with:
          postgresql-version: '15'
      - name: Init database
        run: |
          psql -U postgres -h localhost -p 5432 -c "ALTER USER postgres WITH PASSWORD 'postgres';" || true
          psql -U postgres -h localhost -p 5432 -tc "SELECT 1 FROM pg_database WHERE datname = 'app'" | grep -q 1 || psql -U postgres -h localhost -p 5432 -c "CREATE DATABASE app;"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: |
          pnpm config set node-linker hoisted
          pnpm config set package-import-method copy
          pnpm install --no-frozen-lockfile --ignore-scripts
      - name: Env
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/app" >> $GITHUB_ENV
          echo "DIRECT_URL=postgresql://postgres:postgres@localhost:5432/app" >> $GITHUB_ENV
          echo "JWT_SECRET=secret_for_tests" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_TRPC_URL=http://localhost:4000/trpc" >> $GITHUB_ENV
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> $GITHUB_ENV
      - name: Migration-run-check
        run: bash scripts/ci/migration-run-check.sh
      - name: Seed-run-check (admin-only)
        run: bash scripts/ci/seed-run-check.sh
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Security scan (npm audit)
        run: npm audit --audit-level=high || true
      - name: API Smoke
        run: node -e "console.log('API smoke placeholder')"
      - name: API Tests (unit/integration)
        env:
          NODE_ENV: test
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DIRECT_URL: ${{ env.DIRECT_URL }}
        run: pnpm --filter @repo/api test -- --passWithNoTests=false
      - name: E2E admin check (placeholder)
        run: bash scripts/ci/e2e-admin-check.sh
