name: Deploy to VPS

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, jeeey]
    env:
      DEPLOY_HOST: '127.0.0.1'
      DEPLOY_USER: 'deploy'
      DEPLOY_PORT: '22'
      PROJECT_DIR: '/var/www/ecom'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create source archive
        run: |
          rm -f repo.tar.gz
          git archive --format=tar.gz -o repo.tar.gz HEAD

      - name: Debug env (self-hosted)
        run: |
          echo "HOST=$DEPLOY_HOST PROJECT_DIR=$PROJECT_DIR RUNNER_OS=$RUNNER_OS"

      - name: Upload archive locally (self-hosted)
        run: |
          set -euo pipefail
          mkdir -p "$PROJECT_DIR"
          cp -f repo.tar.gz "$PROJECT_DIR/"

      - name: Extract archive locally (self-hosted)
        run: |
          set -euo pipefail
          mkdir -p "$PROJECT_DIR"
          cd "$PROJECT_DIR"
          tar -xzf repo.tar.gz
          rm -f repo.tar.gz

      - name: Remote setup locally (self-hosted)
        continue-on-error: true
        run: |
          set -euo pipefail
          chmod +x "$PROJECT_DIR/infra/deploy/remote-setup.sh" || true
          INSTALL_POSTGRES=${{ secrets.INSTALL_POSTGRES || '0' }} \
          CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL || '' }} \
          DOMAIN_WEB=${{ secrets.DOMAIN_WEB || 'jeeey.com' }} \
          DOMAIN_ADMIN=${{ secrets.DOMAIN_ADMIN || 'admin.jeeey.com' }} \
          DOMAIN_API=${{ secrets.DOMAIN_API || 'api.jeeey.com' }} \
          PROJECT_DIR="$PROJECT_DIR" \
          bash "$PROJECT_DIR/infra/deploy/remote-setup.sh"

      - name: Remote deploy locally (self-hosted)
        run: |
          set -euo pipefail
          chmod +x "$PROJECT_DIR/infra/deploy/remote-deploy.sh" || true
          PROJECT_DIR="$PROJECT_DIR" \
          GIT_SHA=${{ github.sha }} \
          GIT_RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          NODE_ENV=production \
          bash "$PROJECT_DIR/infra/deploy/remote-deploy.sh"

