name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Write SSH key file
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Upload repository via git archive over SSH
        run: |
          rm -f repo.tar.gz
          git archive --format=tar.gz -o repo.tar.gz HEAD
          ssh -i key.pem -p "${{ secrets.VPS_PORT }}" -o StrictHostKeyChecking=no "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" "mkdir -p '${{ secrets.PROJECT_DIR }}'"
          scp -i key.pem -P "${{ secrets.VPS_PORT }}" -o StrictHostKeyChecking=no repo.tar.gz "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.PROJECT_DIR }}/repo.tar.gz"
          ssh -i key.pem -p "${{ secrets.VPS_PORT }}" -o StrictHostKeyChecking=no "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" "cd '${{ secrets.PROJECT_DIR }}' && tar -xzf repo.tar.gz && rm -f repo.tar.gz"

      - name: Remote setup (install Node/pnpm/PM2/Nginx/Certbot)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: key.pem
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          command_timeout: 30m
          script: |
            chmod +x ${{ secrets.PROJECT_DIR }}/infra/deploy/remote-setup.sh || true
            INSTALL_POSTGRES=${{ secrets.INSTALL_POSTGRES || '0' }} \
            CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL || '' }} \
            DOMAIN_WEB=${{ secrets.DOMAIN_WEB || 'jeeey.com' }} \
            DOMAIN_ADMIN=${{ secrets.DOMAIN_ADMIN || 'admin.jeeey.com' }} \
            DOMAIN_API=${{ secrets.DOMAIN_API || 'api.jeeey.com' }} \
            PROJECT_DIR=${{ secrets.PROJECT_DIR }} \
            bash ${{ secrets.PROJECT_DIR }}/infra/deploy/remote-setup.sh

      - name: Remote deploy (install deps, migrate, build, restart)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: key.pem
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          command_timeout: 60m
          script: |
            chmod +x ${{ secrets.PROJECT_DIR }}/infra/deploy/remote-deploy.sh || true
            PROJECT_DIR=${{ secrets.PROJECT_DIR }} \
            NODE_ENV=production \
            bash ${{ secrets.PROJECT_DIR }}/infra/deploy/remote-deploy.sh

