name: Diagnostics

on:
  workflow_dispatch:

jobs:
  env-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node & pnpm versions
        run: |
          node -v
          pnpm -v
          npm -v
      - name: List workspaces
        run: |
          cat pnpm-workspace.yaml || true
          ls -la
