name: Figma Extract Mapping

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'scripts/figma-extract.mjs'
      - 'infra/figma/**'
      - '.github/workflows/figma-extract.yml'
      - 'infra/ops/trigger-figma.txt'

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Configure git for push
        env:
          PUSH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GH_PAT || github.token }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${PUSH_TOKEN}@github.com/${{ github.repository }}.git
      - name: Run extractor
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN || secrets.FIGMA_API }}
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_ID }}
        run: |
          node scripts/figma-extract.mjs | cat
          node scripts/figma-extract-nodes.mjs | cat
          node scripts/figma-extract-tokens.mjs | cat
      - name: Commit mapping (mapping only, no large nodes)
        run: |
          git add infra/figma/mapping.json apps/mweb/src/tokens.css
          git commit -m "chore(figma): update mapping.json" || echo "no changes"
          git push origin HEAD:main || true
      - name: Generate mweb routes from mapping (nodes optional)
        run: |
          node scripts/figma-generate-mweb.mjs | cat
          git add apps/mweb/src/routes.generated.ts apps/mweb/src/pages
          git commit -m "feat(mweb): generate routes and pages from Figma mapping" || echo "no changes"
          git push origin HEAD:main || true
      - name: Upload nodes.json as artifact (avoid pushing huge file)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: figma-nodes
          path: infra/figma/nodes.json
      - name: Sync Figma assets (images/icons)
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN || secrets.FIGMA_API }}
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_ID }}
        run: |
          node scripts/figma-assets-sync.mjs | cat
          git add apps/mweb/src/assets || true
          git commit -m "chore(mweb): sync Figma assets" || echo "no changes"
          git push origin HEAD:main || true

