name: MWeb Auth E2E

on:
  workflow_dispatch:

jobs:
  e2e-mweb-auth:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        working-directory: scripts/ci
        run: |
          npm ci || npm i
          npx playwright install --with-deps chromium

      - name: Wait for public API health
        run: |
          set -e
          for i in $(seq 1 40); do
            code=$(curl -s -o /dev/null -w '%{http_code}' https://api.jeeey.com/health || true)
            if [ "$code" = "200" ]; then echo "API ready"; break; fi
            echo "waiting for api ($i)"; sleep 3
          done

      - name: Run E2E MWeb Auth test (real flow)
        env:
          MWEB_BASE: ${{ secrets.MWEB_BASE }}
          API_BASE: ${{ secrets.API_BASE }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          MAINTENANCE_SECRET: ${{ secrets.MAINTENANCE_SECRET }}
        working-directory: scripts/ci
        run: node e2e-mweb-auth.mjs

  e2e-admin-generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: e2e-mweb-auth
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        working-directory: scripts/ci
        run: |
          npm ci || npm i
          npx playwright install --with-deps chromium

      - name: Run E2E DeepSeek Generate
        if: false
        env:
          ADMIN_BASE: ${{ secrets.ADMIN_BASE }}
          API_BASE: ${{ secrets.API_BASE }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        working-directory: scripts/ci
        run: node e2e-deepseek-generate.mjs

