name: Deploy mweb

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/mweb/**'
      - '.github/workflows/mweb-deploy.yml'
      - 'scripts/figma-*.mjs'
  workflow_dispatch: {}

concurrency:
  group: deploy-mweb
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOST: ${{ secrets.SSH_HOST || secrets.VPS_HOST || secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.SSH_USER || secrets.VPS_USER || secrets.DEPLOY_USER }}
      DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY || secrets.VPS_SSH_KEY || secrets.DEPLOY_KEY }}
      MWEB_PATH: ${{ secrets.MWEB_DEPLOY_PATH || secrets.WEBROOT_MWEB || secrets.DEPLOY_PATH_MWEB }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps (mweb only)
        run: pnpm --filter mweb install --no-frozen-lockfile

      - name: Build mweb
        run: pnpm --filter mweb build

      - name: Check required secrets
        run: |
          set -e
          for v in DEPLOY_HOST DEPLOY_USER DEPLOY_KEY MWEB_PATH; do
            if [ -z "${!v}" ]; then
              echo "Missing required secret: $v" >&2
              exit 1
            fi
          done

      - name: Create release dir on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_KEY }}
          script: |
            set -e
            export DEPLOY_PATH="${{ env.MWEB_PATH }}"
            mkdir -p "$DEPLOY_PATH/releases/${GITHUB_SHA}"

      - name: Upload build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_KEY }}
          source: "apps/mweb/dist/*"
          target: "${{ env.MWEB_PATH }}/releases/${{ github.sha }}/"

      - name: Activate release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_KEY }}
          script: |
            set -e
            export DEPLOY_PATH="${{ env.MWEB_PATH }}"
            ln -sfn "$DEPLOY_PATH/releases/${GITHUB_SHA}" "$DEPLOY_PATH/current"
            # Optional: keep last 5 releases
            ls -1dt "$DEPLOY_PATH"/releases/* | tail -n +6 | xargs -r rm -rf
            # Try to reload nginx if available
            (command -v sudo >/dev/null && sudo -n systemctl reload nginx) || true

