# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Build Next.js (smoke only)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Minimal permissions
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: 'false'
      PNPM_CONFIG_STORE_DIR: ${{ github.workspace }}/.pnpm-store
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable
      - name: Use pnpm 8.6.10
        run: corepack prepare pnpm@8.6.10 --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ''

      - name: Ensure default pnpm cache path exists (~/.pnpm-store)
        run: mkdir -p "$HOME/.pnpm-store"

      - name: Configure pnpm store dir (project)
        run: pnpm config set store-dir "$PNPM_CONFIG_STORE_DIR" --location project

      - name: Ensure pnpm store dir exists
        run: mkdir -p "$PNPM_CONFIG_STORE_DIR"

      - name: Install dependencies (workspace)
        run: pnpm install --no-frozen-lockfile --store-dir="$PNPM_CONFIG_STORE_DIR"
        working-directory: .

      - name: Build web (Next.js)
        run: pnpm build && pnpm start & sleep 5 && curl -sSf http://localhost:3000 | head -n 5 | cat
        working-directory: apps/web

  # No deployment in this workflow (smoke build only)
