name: Web/Admin Next.js build

on:
  push:
    branches: [ hash, jam, mishash ]
  pull_request:
    branches: [ hash, main, mishash ]

jobs:
  next-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build Web/Admin
        run: pnpm --filter web build && pnpm --filter admin build
