name: Build Android Release APK (Standalone)

on:
  workflow_dispatch:

jobs:
  build_release_apk:
    runs-on: ubuntu-latest
    env:
      CI: true
      REACT_NATIVE_DIR: ../node_modules/react-native
      REACT_NATIVE_NPM_PACKAGE: ../node_modules/@react-native/gradle-plugin
    defaults:
      run:
        working-directory: apps/mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies (workspace)
        run: pnpm install --no-frozen-lockfile --ignore-scripts
        working-directory: .

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK tools
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install ImageMagick and pngcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick pngcheck

      - name: Install required Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Create placeholder assets (icon/splash)
        run: |
          mkdir -p assets
          convert -size 512x512 canvas:white assets/icon.png
          convert -size 512x512 canvas:white assets/adaptive-icon.png
          convert -size 1242x2436 canvas:white assets/splash.png
          convert -size 32x32 canvas:white assets/favicon.png
          pngcheck -v assets/*.png | cat

      - name: Inject android.package for prebuild
        run: |
          node -e "const fs=require('fs');const p='./app.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));j.expo=j.expo||{};j.expo.android=j.expo.android||{};j.expo.android.package=j.expo.android.package||'com.example.ecom';fs.writeFileSync(p,JSON.stringify(j,null,2));console.log('android.package ->',j.expo.android.package);"

      - name: Set EXPO_PUBLIC_TRPC_URL (release)
        run: |
          node -e "const fs=require('fs');const p='./app.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));j.expo=j.expo||{};j.expo.extra=j.expo.extra||{};j.expo.extra.EXPO_PUBLIC_TRPC_URL=process.env.TRPC_URL || 'https://api.jeeey.com/trpc';fs.writeFileSync(p,JSON.stringify(j,null,2));console.log('Updated app.json ->',j.expo.extra.EXPO_PUBLIC_TRPC_URL);"

      - name: Expo prebuild (android)
        run: pnpm dlx expo prebuild --platform android --clean

      - name: Setup Gradle with cache
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-version: wrapper

      - name: Patch settings.gradle for RN gradle-plugin path
        run: |
          SETTINGS=android/settings.gradle
          if [ -f "$SETTINGS" ]; then
            cp "$SETTINGS" "$SETTINGS.bak"
            sed -i '/includeBuild/d' "$SETTINGS"
            echo 'includeBuild("../node_modules/@react-native/gradle-plugin")' >> "$SETTINGS"
            echo "Patched $SETTINGS:" && head -n 30 "$SETTINGS" | cat
          fi

      - name: Ensure gradle.properties has RN paths
        run: |
          GP=android/gradle.properties
          {
            echo "REACT_NATIVE_NPM_PACKAGE=../node_modules/@react-native/gradle-plugin"
            echo "reactNativeDir=../node_modules/react-native"
            echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
            echo "org.gradle.daemon=true"
            echo "org.gradle.parallel=true"
          } >> "$GP"
          echo "Wrote $GP:" && tail -n 20 "$GP" | cat

      - name: Assemble release (Gradle)
        run: |
          cd android
          chmod +x ./gradlew
          # Retry Gradle in case of transient network/download issues
          for attempt in 1 2 3; do \
            ./gradlew -PREACT_NATIVE_NPM_PACKAGE=../node_modules/@react-native/gradle-plugin -PreactNativeDir=../node_modules/react-native :app:clean :app:assembleRelease --no-daemon --stacktrace && break || { \
              echo "Gradle attempt $attempt failed"; \
              if [ "$attempt" -lt 3 ]; then sleep $((attempt*15)); else exit 1; fi; \
            }; \
          done

      - name: Generate temporary release keystore
        run: |
          cd android/app
          keytool -genkey -v -keystore release.keystore -alias release -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=example, OU=dev, O=company, L=city, S=state, C=US"

      - name: Zipalign and sign APK
        run: |
          cd android/app/build/outputs/apk/release
          APK_UNSIGNED=app-release-unsigned.apk
          if [ ! -f "$APK_UNSIGNED" ]; then echo "Unsigned APK not found"; ls -la; exit 1; fi
          BUILD_TOOLS=$(ls -v "$ANDROID_SDK_ROOT"/build-tools | tail -1)
          "$ANDROID_SDK_ROOT"/build-tools/$BUILD_TOOLS/zipalign -v -p 4 "$APK_UNSIGNED" app-release-aligned.apk
          # keystore created at android/app/release.keystore; relative path from release dir requires going up 4 levels
          "$ANDROID_SDK_ROOT"/build-tools/$BUILD_TOOLS/apksigner sign --ks ../../../../release.keystore --ks-pass pass:android --key-pass pass:android --out app-release-signed.apk app-release-aligned.apk
          "$ANDROID_SDK_ROOT"/build-tools/$BUILD_TOOLS/apksigner verify app-release-signed.apk

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: apps/mobile/android/app/build/outputs/apk/release/app-release-signed.apk
          if-no-files-found: error

