name: Build Android Release APK (Standalone)

on:
  workflow_dispatch:
  push:
    branches:
      - 'cursor/**'
      - 'auto-fix/**'

jobs:
  build_release_apk:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: apps/mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies (workspace)
        run: pnpm install --no-frozen-lockfile
        working-directory: .

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK tools
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Create placeholder assets (icon/splash)
        run: |
          node -e "const fs=require('fs');const b='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO9n3aQAAAAASUVORK5CYII=';fs.mkdirSync('assets',{recursive:true});const buf=Buffer.from(b,'base64');['icon.png','adaptive-icon.png','splash.png','favicon.png'].forEach(f=>fs.writeFileSync('assets/'+f,buf));console.log('Wrote assets');"

      - name: Inject android.package for prebuild
        run: |
          node -e "const fs=require('fs');const p='./app.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));j.expo=j.expo||{};j.expo.android=j.expo.android||{};j.expo.android.package=j.expo.android.package||'com.example.ecom';fs.writeFileSync(p,JSON.stringify(j,null,2));console.log('android.package ->',j.expo.android.package);"

      - name: Set EXPO_PUBLIC_TRPC_URL (release)
        run: |
          node -e "const fs=require('fs');const p='./app.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));j.expo=j.expo||{};j.expo.extra=j.expo.extra||{};j.expo.extra.EXPO_PUBLIC_TRPC_URL=process.env.TRPC_URL || 'https://jeeeyai.onrender.com/trpc';fs.writeFileSync(p,JSON.stringify(j,null,2));console.log('Updated app.json ->',j.expo.extra.EXPO_PUBLIC_TRPC_URL);"

      - name: Expo prebuild (android)
        run: pnpm dlx expo prebuild --platform android --clean

      - name: Assemble release (Gradle)
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew :app:clean :app:assembleRelease --no-daemon --stacktrace

      - name: Generate temporary release keystore
        run: |
          cd android/app
          keytool -genkey -v -keystore release.keystore -alias release -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=example, OU=dev, O=company, L=city, S=state, C=US"

      - name: Zipalign and sign APK
        run: |
          cd android/app/build/outputs/apk/release
          APK_UNSIGNED=app-release-unsigned.apk
          if [ ! -f "$APK_UNSIGNED" ]; then echo "Unsigned APK not found"; ls -la; exit 1; fi
          BUILD_TOOLS=$(ls -v "$ANDROID_SDK_ROOT"/build-tools | tail -1)
          "$ANDROID_SDK_ROOT"/build-tools/$BUILD_TOOLS/zipalign -v -p 4 "$APK_UNSIGNED" app-release-aligned.apk
          # keystore created at android/app/release.keystore; relative path from release dir requires going up 4 levels
          "$ANDROID_SDK_ROOT"/build-tools/$BUILD_TOOLS/apksigner sign --ks ../../../../release.keystore --ks-pass pass:android --key-pass pass:android --out app-release-signed.apk app-release-aligned.apk
          "$ANDROID_SDK_ROOT"/build-tools/$BUILD_TOOLS/apksigner verify app-release-signed.apk

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: apps/mobile/android/app/build/outputs/apk/release/app-release-signed.apk
          if-no-files-found: error

