name: Scheduled Uptime Check

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check admin health
        run: |
          set -euo pipefail
          for i in $(seq 1 5); do
            curl -fsS -k https://admin.jeeey.com/api/admin/health -m 20 -o /dev/null && exit 0 || sleep 5
          done
          echo 'admin health failed after retries' >&2
          exit 1
      - name: Check api health (public)
        run: |
          set -euo pipefail
          for i in $(seq 1 5); do
            curl -fsS -k https://api.jeeey.com/health -m 20 -o /dev/null && exit 0 || sleep 5
          done
          echo 'api health failed after retries' >&2
          exit 1
