name: verify_public_endpoints

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prime known_hosts
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          mkdir -p ~/.ssh
          if [ -n "$VPS_HOST" ]; then ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts 2>/dev/null || true; fi

      - name: Run HTTPS/API checks from VPS (avoids runner egress issues)
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL || 'admin@example.com' }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD || 'admin123' }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          set -e
          HOST="${VPS_HOST:-}"
          if [ -z "$HOST" ]; then echo "VPS_HOST not set" >&2; exit 1; fi
          ssh -o StrictHostKeyChecking=no root@"$HOST" "ADMIN_EMAIL='${ADMIN_EMAIL}' ADMIN_PASSWORD='${ADMIN_PASSWORD}' bash -s" <<'REMOTE'
          set -e
          : "${ADMIN_EMAIL:=admin@example.com}"
          : "${ADMIN_PASSWORD:=admin123}"
          echo "=== jeeey.com HEAD ==="
          curl -ksS -I https://jeeey.com | sed -n '1,12p'
          echo
          echo "=== admin.jeeey.com HEAD ==="
          curl -ksS -I https://admin.jeeey.com | sed -n '1,12p'
          echo
          echo "=== m.jeeey.com HEAD ==="
          curl -ksS -I https://m.jeeey.com | sed -n '1,12p'
          echo
          echo "=== m.jeeey.com HTML snippet ==="
          curl -ksS https://m.jeeey.com | sed -n '1,40p' | sed 's/<[^>]*>//g' | tr -s ' ' | head -n 5
          echo
          echo "=== api.jeeey.com /health ==="
          curl -ksS -i https://api.jeeey.com/health | sed -n '1,20p'
          echo
          echo "=== admin login (form) headers ==="
          curl -ksSI -X POST https://api.jeeey.com/api/admin/auth/login \
            -H 'content-type: application/x-www-form-urlencoded' \
            --data "email=${ADMIN_EMAIL}&password=${ADMIN_PASSWORD}" | sed -n '1,60p'
          echo
          echo "=== admin login (json) status ==="
          curl -ksS -o /dev/null -w '%{http_code}\n' -X POST https://api.jeeey.com/api/admin/auth/login \
            -H 'content-type: application/json' \
            --data "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\",\"remember\":true}"
          REMOTE

